### ISSUE TITLE
convert_utc fails

### ISSUE THREAD

**Issue by bbrendon** [home-assistant/appdaemon#104]
aimc. Let me know if you want me to dig out those errors again.

**Comment by bbrendon** [comment]
I just saw your discord. I'll get on it now.

**Comment by bbrendon** [comment]
I found the errors.
https://hastebin.com/ekojequrom.rb

Python 3.5.3

**Comment by acockburn** [comment]
I took a look - this is a different error and is not being caused by `convert_utc()` - the issue is that `convert_utc()` returns a python datetime object, and the `log()` function is expecting a string so can't print it out. If you convert the datetime back to a string before logging it you should be fine.

**Comment by bbrendon** [comment]
Thanks
