### ISSUE TITLE
Update to latest hadaemon

### ISSUE THREAD

**Issue by curtisolson** [home-assistant/appdaemon#148]
Can we update to pull in the latest 2.1.8 or 2.1.9 hadaemon? The version is out of date with the docs and as a new user, I spent a lot of time confused about configurations and apps not working.

I'm happy to help but I'm not that familiar with docker. Maybe with some guidance, I can do a pull request and test. It looks like the install command in the docker file is this. 

`pip install git+https://github.com/home-assistant/appdaemon.git@master`

But, to me, that seems like it should get the lastest code. 

Thx!

**Comment by acockburn** [comment]
Hi there - I assume you are talking about the hass.io addon? Unfortunately I don't control that it was created by @vkorn.  I have PMed him but he hasn't responded. I have little incentive to make an addon myself because I am working towards an alternative - include AppDaemon and AHDashboard as a native piece of Home Assistant. At that popint, it should just work with HASS.IO with no need for an addon.
