### ISSUE TITLE
unclear documentation, call_service

### ISSUE THREAD

**Issue by quazzie** [home-assistant/appdaemon#178]
Example uses "light/turn_on" but parameter description and synopsis uses "light.turn_on".
What is it? 

And if it's slash why is it changed from standard ha notation of "light.turn_on" ?
Also if it's slash is it changed for anything else ? 
Are entity_ids changed to slash also ?

**Comment by acockburn** [comment]
an you provide me with a link to the incorrect doc please, it is in several places.

The first version of AppDaemon used light.turn_on but I changed it before release to use a "/" instead since this is the way it is accessed in the rest interface and presented in the logs (I also recall it was this way on the dev tools page but I might be wrong). Entites are separated with "." and always have been, and nothing has changed in this area in the last 18 months.

So, if we have an incorrect doc somewhere let me know where so I can fix it.

**Comment by quazzie** [comment]
Sorry, forgot the link :(
http://appdaemon.readthedocs.io/en/latest/APIREFERENCE.html#services

**Comment by acockburn** [comment]
Thanks - this will be fixed in version 3.0
