### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by fabaff** [home-assistant/appdaemon#230]
When one run `appdaemon` with no parameter then you get a traceback. It would be more user-friendly to show the help output.

```bash
$ appdaemon
Traceback (most recent call last):
  File "/home/fab/Documents/repos/home-assistant-appdaemon/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/home/fab/Documents/repos/home-assistant-appdaemon/lib64/python3.6/site-packages/appdaemon/admain.py", line 198, in main
    config.read_file(open(config_file_conf))
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by acockburn** [comment]
Hi Fabian, thanks. The traceback looks like its from 2.1.12 or earlier, and the code has changed in this area in 3.0. In particular, use of the .cfg file type has been deprecated so that code no longer exists. However, there was an analogous error in loading up the yaml config so I tidied that up to give a sane error message and list the help. That fix will be in 3.0beta2 which I'll be releasing shortly.
