### ISSUE TITLE
Coding standards and PEP8

### ISSUE THREAD

**Issue by yawor** [home-assistant/appdaemon#27]
Hi,

I've been reading through the source code of AppDaemon. To be honest it's really hard to read. I don't know if there are any plans to make the code PEP8 compliant in the future but I've been thinking about formatting the code myself and submitting a PR. So if the author has nothing against it I can do it. So please let me know in the comment.

**Comment by acockburn** [comment]
Not sure that I agree it's hard to read, but I am relatively new to Python and haven't been exposed to PEP8, so I guess if you are used to that format it could be challenging - if you are happy to reformat I am happy to take it as a PR and accept it as a learning process and maintain it going forward :)

If you do decide to go ahead can I ask that you submit the PR after the next major release - I am gettingready to release 1,5.0 and it has quite a few changes. Rather than merge I would prefer you submit against that version as it should be the last for a while. I am planning to release it at the weekend.

**Comment by yawor** [comment]
No problem. I can wait for the next release. I've been able to identify some issues with the code besides formatting. For example you shouldn't check if something is False or True using equality operation (==) but you should use `is` keyword (`if foo is False` for example). I'll try to find such issues and also correct them.

**Comment by SupahNoob** [comment]
Andrew, I've also noticed this but for what it's worth, I've never had a problem understanding your logic. I'm self-taught Python over the past few years, and it's a bit obvious you didn't start with Python as a cs lang, but that's totally fine. @yawor thanks for taking on this endeavor!

**Comment by acockburn** [comment]
1.5.1 is now live. I'll close this and await the PR - thanks!
