### ISSUE TITLE
Reopen of  #189 - Input Select changes to first item in list when page reaload in dashboard

### ISSUE THREAD

**Issue by nicholh** [home-assistant/appdaemon#325]
This problem was rectified however seems to have come back with an upgrade of ha/appdeamon.

Summary below:
I have noticed a problem in Appdeamon Dashboard wherby on a dashboard load/reload input select widgets momentaraily change to the first item in the list then back to the previosly selected item.

In more detail:

set Input select in HA/Dashbaord is set to any value other than the first in the list
load or reload a dashboard that includes an input select widget associated to the the HA input select object.
Input select value is monantarilly set to the first object in the list (this is not just in the Dashboard, it updates the object in HA also.
the input select value then reverts to the origial selected value (n.b. sometime (about 10% of the time the value does not revert and stays as the first value)
Expected Behavior: no change to input select unless new value is selected.

This casues a problem where outomations in HA are triggered from input selected changes.

**Comment by ReneTode** [comment]
i think this can be something browser related.
i created the input_select myself and i use it myself also, but i never saw something like that.
i just reread the code and i dont see how it can happen, other then that the browser makes a selection when the input_select is filled.
in which browser do you have the problem?
can it be cash related?
can it be that the browser stored the option? most browsers have the option to store form field and they fill the field if a form is loaded. the input_select is a form field, so the browser can fill it to a stored setting.

**Comment by nicholh** [comment]
Thanks for your reply,

I have tried this across a bunch of different browsers and have seen the problem across all of them.

Basically it looks like when the page is loading very quickly the input select is set to the first item in the list and nearly instantly it changes to what was previosly selected.  This sometimes triggers automations in Home Assitant based on the change to the input select - Note: this does not always happen, however can be obseved after a few page refreshes.

Unfortuantly my python skills are not good enought (pretty much non-exisitant)  to troubleshoot. 

As seen in isse 189 this was a problem however was rectified with the release off appdeamon 3. It seem to have recently come back with a home assitant upgrade.

I am happy to do troupleshooting if somebody can point me in the right direction.

Thanks,
Nichol

**Comment by ReneTode** [comment]
this has nothing to do with python, its completely javascript.

the fact that it isnt happening always, but it happens after a few page refreshes, makes it clear that its a browser thing.

the version from home assistant and an upgrade from that can in no way have influence on it.

i am pretty sure it has to do with cash in the browser.
try firefox and disable cash completely. (i say firefox, because i have found that with firefox complete disable from cash is quite simple)

i did lookup what andrew has changed 6 months ago and i see he added a check and the first change is ignored now. so ithink that all that can happen is that the browser doesnt reload the code when the page is reloaded (that comes down to cash again)
