### ISSUE TITLE
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://<homeassistant>/api/services/

### ISSUE THREAD

**Issue by eifinger** [home-assistant/appdaemon#345]
When Homeassistant restarts all apps are Initializing.
`self.call_service` **Sometimes** this leads to the error:
`requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://homeassistant.kevineifinger.de/api/services/`

I wrap my service calls in try/except statements and just retry the service call until it succeeds.
You can see an example how I do it [here](https://github.com/eifinger/appdaemon-scripts/blob/a6783c75bb8b7ca2435a27815dd20b310921cf6b/isUserHomeDeterminer.py#L83)

Should this be the default behaviour of appdaemon?

**Comment by ReneTode** [comment]
yes it is.
if you dont want apps to restart when HA restarts you can place the line:
```
  plugin: NONE
```
in your app's yaml
but some apps will trow errors when they cant reach HA and keep running

so please close the issue.

**Comment by eifinger** [comment]
I want my apps to restart and initialize again when HA is restarting. And is is generally best practice to assume that any rest call can fail.
I just was suggesting that appdaemon can retry x times as default for Hass service calls. Rather than letting the user wrap every single Hass call (at least during initialize) in try except statements.
 If I am not mistaken that is what for example the requests lib is doing.

**Comment by ReneTode** [comment]
i dont think you are insulting anyone. ;)
in general, AD should stop trying to send things to HA when it cant reach HA. and apps are reinitialised when HA is restarted.

the biggest problem with this is that HA sends a signal that its up and running and then it starts to setup the components.
if components take more time loading then AD takes to initialise then you will get errors.

there is the possibilty to set a delay after HA is noticed again, but it will be to much for some and to little for others (i think Andrew had something like that in AD 2)

service call is just 1 function. there is no way to determine if it comes from the initi or from somewhere else. so the only option would be a multi retry for all, but that can cause trouble too, because the service call doesnt give feedback.

normally there are little service calls in the inits. (i have lots of apps and nowhere a service call in the init.)
i think you can avoid those errors/problems by using a listen_state for a certain element in HA and then set the service call in the callback, or use a run_in in the init to set a delay, so you are sure HA is running.

but i just looked at your code and its not in the initialise.
the callback shouldnt be activated at all when HA is down.
after HA is up again, the app gets reinitialised and the callback should be closed anyway.

i think there might be a problem in the order things are done in AD it should be:
- AD sees HA down
- AD shuts down all app that must be reinitialised
- AD waits untill HA is back
- AD initalises all app that need to intialised.

and your problem show that in the moment it is:

- AD sees HA down
- AD waits untill HA is back
- AD shuts down all app that must be reinitialised
- AD initalises all app that need to intialised.

i think that @acockburn  needs to look at that, and tell me if i am right.
