### ISSUE TITLE
Mixed MQTT / HA architecture

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#430]
_To start with, I apologise if this is not the correct place to ask such general questions. I will be glad to do a PR for the documentation (if there is interest) once I have figured my problem out._

**The context:**

I have several devices:

- Sonoff Basic switches, which speak MQTT
- a Sonoff RF Bridge which listens to incoming RF433 messages from Dumb Switches, then sends an MQTT message
- Dumb Switches (I use this name because these switches do not keep state, they just send a message "I was pressed")

After trying for a short while HA and Appdaemon, I wrote my own orchestrator code which 
- listens to MQTT
- depending on what is published makes decisions based on scenarios
- sends a relevant MQTT message base on the scenario

I now realize that
- defining my objects (switches, lights, radios, etc.) in HA is a much better solution
- the automation mechanism in HA is dreadful
- Appdaemon is the way to go to bind my own "business logic" with the logistics aspects of HA (ability to switch on off lights etc)

As an example, two typical scenarios could be
- a chain of events
  - a dumb switch is pressed, 
  - this is detected by the RF Bridge which sends `8716151414` (the code received on RF, unique to a dumb switch) to the topic `dumb_switch`, 
  - this is detected by the orchestrator which toggles `light1` by sending an MQTT message `TOGGLE` to topic `room/light1`, 
  - which is retrieved by `light1`, which toggles itself
- a temporal event
  - in a loop, the current time is compared to the sunset time, 
  - and if we are 15 minutes before it, 
  - a message is sent to `light2` so that it switches on

I would like to port such scenarios to Appdaemon. I read the docs to get a general understanding of the API but before jumping in I want to make sure that I do not go the wrong way (and especially - reinvent the wheel by writing too much of my own code)

**My general questions are:**

- am I correct assuming that I will define my objects in HA and just refer to their functionality ("switch the light in the living room on"), leaving to HA the command and state feedback management?

- in the case of the RF bridge, I have raw MQTT messages I will need to handle and maintain the mapping between the messages and the actual devices. Is this something I should have in the Appdaemon code, or should this be configured in HA?

- should I use the MQTT modules of Appdaemon, or use modules such as `paho-mqtt` to handle the MQTT traffic?

As I mentioned (and again, if there is of course interest) I would be glad to append to the docs a down-to-earth example of porting some more complex scenarios, especially for HA/MQTT mixed scenarios.

**Comment by acockburn** [comment]
Hi There - 

`am I correct assuming that I will define my objects in HA and just refer to their functionality ("switch the light in the living room on"), leaving to HA the command and state feedback management?`

Correct. If Home Assistant is handling the MQTT aspects for you, it abstracts the functionality so that an MQTT switch is a first clas citizen like a ZWave switch or a Hue switch. AppDaemon can work with any of the Home Assistant entities in an appropriate way, e.g. `self.turn_on("switch.my_mqtt_switch")

`in the case of the RF bridge, I have raw MQTT messages I will need to handle and maintain the mapping between the messages and the actual devices. Is this something I should have in the Appdaemon code, or should this be configured in HA?`

I believe it is possible to get down to the MQTT message level by looking at MQTT specific event, which again will be sent up to AppDaemon for processing

`should I use the MQTT modules of Appdaemon, or use modules such as paho-mqtt to handle the MQTT traffic?`

If you are using HASS, you would not need any MQTT specific support in AppDaemon or directly within your apps themselves. If you wanted to use other aspects of HASS such as it's built in automation, or Alexa support for instance this is a reasonable way to go. If however, you want to use HASS soley as an interface to MQTT, I would suggest that instead you use AppDaemon;s built in MQTT functionality to go direct to MQTT. This exposes the messages themselves as topics you can subscribe to and send to, whcih might make more sense. In this case the underlying MQTT code uses paho-mqtt but it's built into the AppDaemon code so you wouldn;t have to worry about it, just use the supplied API to subscribe to topics and send messages.

Hope this helps - and if you do decide to go down this route I would love to see some examples of what you create for inclusion in the docs.
