### ISSUE TITLE
variable camera entitity Token

### ISSUE THREAD

**Issue by Sygu00** [home-assistant/appdaemon#506]
Hi,
since in HASSIO 0.86.3, my cam widget in HADasboard doesn't show the cam picture when the cam token changes. But in earlier versions,( my last one was 0.85.1) the token didn't change at all, so there was no problem. My widget config is as shown:

camara_entrada:
    widget_type: camera
    widget_style: "background: #c1c5c9;"
    refresh: 60
    title: Camara Entrada
    entity_picture: http://192.168.X.Y//api/camera_proxy/camera.camera?token=my_cam_TOken

How can i fix this?

Regards

Sergio

**Comment by ReneTode** [comment]
if HA changed something to change the way the token behaves, i am afraid that all you can do is go back to HA 0.85.1 if you want the dashboard show your cam.

it might be worth a try to set api_key in homeassistant (which is deprecated) and try to use api key instead of token. (some cams did work without token untill now)

in the near future we will work on changing dashboard and the camera widget is 1 of the main things that will change, but that can be a while.

**Comment by acockburn** [comment]
This should be addresses by the new camera widget
