### ISSUE TITLE
utils.find_path ignores CWD

### ISSUE THREAD

**Issue by ahknight** [home-assistant/appdaemon#517]
The find_path function only looks at two hard-coded locations for files.  If I start appdaemon and use a relative path to the config dir then I'm erroneously told that there is no appdaemon section in my config file and no apps are loaded.  By altering the command to "$PWD/conf" instead of "conf" everything magically works.

When looking for a file, it's generally expected to check the current working directory first as not all installs will be in the same locations.

**Comment by ReneTode** [comment]
indeed not all installs are in the same place that is why a full path is expected.
appdaemon cant check the parent directories for wrong fileright settings if the full path isnt given.

also its mostly used as a service where a full path is neccesary.

**Comment by ahknight** [comment]
Well, then let's back up a bit.  The problem is that the tool when invoked doesn't tell the user that a non-absolute path was used and that's the reason for the failure to start.  If an absolute path is absolutely required then any path argument that doesn't start with a directory separator should give the user a clear error.

I lost about 30m searching for answers until a random forum post mentioned trying absolute paths.

**Comment by ReneTode** [comment]
thats probably because the creator expects that someone who starts appdaemon for the first time reads in the docs how to do that and there is clearly stated that a full path is expected.

thats my advise in that case, next time look at the docs before searching the forum ;) 
https://appdaemon.readthedocs.io/en/latest/index.html

its very hard to test if the right path is given, the only thing that can be done is see if the appdaemon.yaml is in the given path.
but maybe that Andrew sees an option to improve with your suggestion.  (allthough thats very hard, because when your system is setup right its also possible to use relative path (i have seen such cases, and i think hassio also doesnt use full path))
the most important thing is that AD knows where to find the needed files, and the easiest way for that is full path.

**Comment by ahknight** [comment]
If relative paths are so difficult, then I wonder how 50 years of UNIX/POSIX tools managed to work at all.

**Comment by ReneTode** [comment]
i meant that it isnt just as simple as checking for a /
but if its that simple, then i guess you know how and can add a PR, i am sure Andrew wont mind.

but i am sure there is a reason why he chose full path and did write it in the docs.
and maybe that reason has gone while developing AD, so it might be an option for the future.

by the way if its simple i would like to know too, because i tried several times to give a relative path in my apps, but somehow it never works.

**Comment by challs** [comment]
Hi, I ran into this one as well. I can see that commit cef2722ae4914993d6810494406120068e3a723a already fixed it and is present on the `dev` branch. The fix allows you to specify the config directory as a relative path.

**Comment by acockburn** [comment]
Yep, fixed in dev and available in 4.0b1 so closing this
