### ISSUE TITLE
What does "Excessive time spent in utility loop" mean?

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#751]
I saw the following, isolated event in my log:

    2019-10-06 09:58:30.580023 WARNING AppDaemon: Excessive time spent in utility loop: 5020.0ms

When is the issue raised? Is the "utility loop" something I control or have influence on?

**Comment by ReneTode** [comment]
the utilityloop is the internal loop from AD.
this issue is raised when AD needs to spend to much time inside some apps, and or when at restart from app the initialisation process takes to long.

allthough the problem is less severe inside apps in AD 4 then in AD 3, its still important to create your apps correctly.

inside a callback it important to use what i call "the hit and run" stategy.
make sure that every callback takes up the shortest possible time, so no use off sleep, or loops, etc.

i noticed myself that the use of requests has a bad influence on the performance from AD.
so reduce that to the minimal needed and balance your actions (for example, if you create 5 sensors with AD that all use requests every minute, then make sure they dont run together, but 12 seconds apart from each other)

**Comment by dlashua** [comment]
I have an App Class that is used by about 40 apps. Initialize isn't particularly taxing, there is no sleep, and the callbacks don't do any loops. However, I still see this warning every time I modify the app class and all 40 apps restart at the same time.

It's an indication that something MIGHT be a problem, but not that it is DEFINITELY a problem. If it happens on it's own, without you actively changing something at the time, it's worth looking into to see what might be causing the issue. When the utility loop is excessively busy, it means that other scheduled callbacks might not fire on time.
