### ISSUE TITLE
Make appdaemon4 available for HassIO Add-on

### ISSUE THREAD

**Issue by thundergreen** [home-assistant/appdaemon#833]
Hi friends. I'm now waiting month to get HassIO add-on for appdaemon V4 ..is there a planning about to release those ?

Best regards

**Comment by ReneTode** [comment]
hi @thundergreen AD 4 beta is planned for release for a while now, but IRL from devs has delayed that over and over.
i still only can say, that if nothing goes wrong anymore then soon.
but how soon after that there will be an AD 4 addon we cant say, because we dont maintain and create addons.

**Comment by thundergreen** [comment]
Well.. once you give AD4 the kick-off.. the addon will be created by frenck. afaik

**Comment by ReneTode** [comment]
lets hope so, because when we moved from AD 2 to AD 3 he also created a beta addon.

**Comment by acockburn** [comment]
Have been in discussions with @frenck and he is ready to go as soon as we release 4.0 - HASS has tightened up rules a little and no longer create beta addons for hass.io, so he has been waiting for the AD team to release 4.0 which we are working on and hope to get out soon.

**Comment by chbndrhnns** [comment]
I would appreciate a new release to get access to the fix from https://github.com/home-assistant/appdaemon/issues/773

**Comment by benleb** [comment]
is there a list of blockers/todos or anything for AD4? Maybe some people would like to contribute to speed things up a little 👍

**Comment by ReneTode** [comment]
@benleb we are rediscussing what we consider blockers/todos
there is/was a list, but not public.

the main problem is that Andrew is really needed for a release, and his life is quite complicated at this point, so he has very little time.

**Comment by benleb** [comment]
Okay, sounds i have to backport more of my apps to ad3...^^

Why is the todo-list a secret? :D

But besides that, that's not good. not for @acockburn (bearing all responsibility probably generates some kind of "pressure" and such...) nor for appdaemon. the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) should be increased somehow maybe...?!

**Comment by acockburn** [comment]
Plan is to get AD4.0 out by the end of Jan.

As regards pressure - I can handle it ;) If it gets too much I step away for a little while. I've had far too many hobbies ruined by pressure to let this become one. The price paid for that is that sometimes releases can be a little delayed. This time I've had a lot of busyness in work life coupled with some personal things to work through which is what has been delaying 4.0. In discussion with the team I took the decision to delay a couple of pieces of planned work and release 4.0 as soon as possible so we could get support for python 3.8 out there and a hass.io addon for AD 4.0 which can't happen until we are out of beta.

The ToDo list is "secret" because if we start mentioning things people will want them ASAP and we are back to the pressure thing. Since this is a hobby for me I don't want to be in that situation.

If I ever figure out a way to make AD my full time job we will be better about feature velocity and release schedules!

**Comment by ReneTode** [comment]
@benleb bearing all responsibility comes when you create something that others like, and that you develope as your baby.
Appdaemon is and will be Andrews responsibility, but these days he got a team to support him to do the things he does best in the little time he has got.

Thats why i am the voice of AD for years now, so that Andrew doesnt have to deal with that kind of things.

we are also preparing AD more and more so that it can be expanded by users/developers, so that we dont need that much big version changes anymore.

**Comment by frenck** [comment]
Let's close this one up, since the add-on has been released.
