### ISSUE TITLE
New config parameters required in AD4.0

### ISSUE THREAD

**Issue by cornim** [home-assistant/appdaemon#835]
Hi,

I'm trying out the new AD 4.0.0b2 and realized, that now a couple of additional parameters are mandatory in the config file: In particular these are:
```
latitude (required) - latitude for AppDaemon to use.
longitude (required) - longitude for AppDaemon to use.
elevation (required) - elevation for AppDaemon to use.
time_zone (required) - timezone for AppDaemon to use.
```
Unfortunately I don't see any indications in the documentation on how to format these and what units to use. For each of them there are several possibilities.

Additionally I would like to understand why these have been moved from optional to mandatory. Why can they no longer be read from HA?

As an aside: Do I read the documentation correctly, that, in the absence of a log section, all log messages are still redirected to STDOUT?

**Comment by cornim** [comment]
Also the `conf/appdaemon.yaml.example` is missing these entries.

**Comment by ReneTode** [comment]
if there are several options to format those then indeed we need to specify in the docs.
i am pretty sure that its possible just to copy paste it from HA.

they cant be read from HA anymore because HA is optional. AD can be used without using HA.
but without timezone, etc. it is not possible to have sun based functions

logs are logged to STDOUT or STDERR on default.

we will change the example file also.

thx for pointing out these issues.

**Comment by cornim** [comment]
Just to clarify: Possible formatting options that come to my mind are:
lat/long: floating point numbers or degrees + minutes + secs
time zone: UTC+<number> or string timezone e.g. Europe/Paris
elevation: different units are possible, e.g. imperial or metric.

**Comment by benleb** [comment]
we should do it like the huge majority from my opinion... and not invent some strange units or formats...
* floats for lat/long
* timezone as X/Y string
* elevation in meters as imperial is lol and really uncommon

here a working (running since months...) snippet from my config...
```
  time_zone: Europe/Berlin
  latitude: 46.716962
  longitude: 8.096265
  elevation: 505
```

**Comment by acockburn** [comment]
As Rene said, the format is identical to HA, no strange formats being invented here! We'll add to the docs.

**Comment by cornim** [comment]
Works for me.
I didn't want to promote any other formats. Just wanted to point out that the formatting wasn't clear from the docs.

**Comment by acockburn** [comment]
OK, hints have been added to the docs in dev.

**Comment by sillyfrog** [comment]
Not sure if I should open a new issue, but further to this, this doc also needs to be updated: https://github.com/home-assistant/appdaemon/blob/dev/docs/DOCKER_TUTORIAL.rst

I have not used AppDaemon yet and just getting started, and this is the first thing I have hit. Cheers.

**Comment by onedr0p** [comment]
@acockburn could it be made so that these can be overridden by the environment variables, and not mandatory in the `appdaemon.cfg`? This would make the UX of using Docker with appdaemon much easier.

Reference: I am building a helm chart for Kubernetes over at https://github.com/k8s-at-home/charts/pull/326

**Comment by ReneTode** [comment]
even the fact that you speak about appdaemon.cfg shows that you are not a real user from AD.

the reference to appdaemon.cfg is old, and should be changed, but any person who really used AD should at least know the configuration files from AD.
please read the docs, so that you know what configuration file AD uses.

**Comment by onedr0p** [comment]
Wow what a condescending and arrogant reply.  Sorry I mistyped `.cfg`, I meant `.yaml`

**Comment by ReneTode** [comment]
ok, sorry that i was a bit snappy.
